apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: yvmi
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-srqq-tenant/byoc-app-uxht/yvmi@sha256:669508221f38923369aa0e64d0e8da9b28445ec01ef0f2ec4cfb19c354e8ae93
        name: my-java-quarkus
        resources: {}
status: {}
