apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: yvmi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yvmi
    app.kubernetes.io/part-of: byoc-app-uxht
  name: yvmi
spec:
  rules:
  - host: yvmi-byoc-srqq-tenant.apps.107d2c8e9618783ac43b.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: yvmi
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
