apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: yvmi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yvmi
    app.kubernetes.io/part-of: byoc-app-uxht
  name: yvmi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: yvmi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: yvmi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-srqq-tenant/byoc-app-uxht/yvmi@sha256:669508221f38923369aa0e64d0e8da9b28445ec01ef0f2ec4cfb19c354e8ae93
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
